server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: kafka # kafka rocketMQ tcp
  mqServers: 172.16.254.29:9092 #or rocketmq
  #canalServerHost: 127.0.0.1:11111
  #mode: tcp 
  zookeeperHosts: 172.16.254.29:21811,172.16.254.29:21812,172.16.254.29:21813
  flatMessage: true
  batchSize: 50
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey: 
  secretKey: 
  kafka:
    security:
      protocol: SASL_PLAINTEXT
    sasl:
      mechanism: PLAIN
      jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="bob" password="bob-pwd"
  srcDataSources:
    etl_odoo:
      url: jdbc:mysql://172.16.254.40:3306/etl_odoo?autoReconnect=true
      username: root
      password: root
    odoo:
      url: jdbc:mysql://172.16.254.41:3306/odoo?autoReconnect=true
      username: root
      password: root      
  canalAdapters:
  - instance: etl_odoo_etl_product_info
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 172.16.254.29:8200
        properties:
          accessId: xxx
          accessKey: xxx
          cluster.name: docker-cluster
  - instance: odoo_product_template
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 172.16.254.29:8200
        properties:
          accessId: xxx
          accessKey: xxx
          cluster.name: docker-cluster

#      - name: logger
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase

