server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: kafka
  mqServers: 172.16.254.29:9092
  zookeeperHosts: 172.16.254.29:21811,172.16.254.29:21812,172.16.254.29:21813
  flatMessage: true
  batchSize: 150
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey: 
  secretKey: 
  srcDataSources:
    etl_odoo:
      url: jdbc:mysql://172.16.254.40:3306/etl_odoo?autoReconnect=true
      username: root
      password: root
    odoo:
      url: jdbc:mysql://172.16.254.41:3306/odoo?autoReconnect=true
      username: root
      password: root      
  canalAdapters:
  - instance: etl_odoo_etl_product_info
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 172.16.254.29:8200
        properties:
          accessId: xxx
          accessKey: xxx
          cluster.name: docker-cluster
  - instance: odoo_product_template
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 172.16.254.29:8200
        properties:
          accessId: xxx
          accessKey: xxx
          cluster.name: docker-cluster
